let site,menu,user;const $=s=>document.querySelector(s);const clone=x=>JSON.parse(JSON.stringify(x));const esc=s=>String(s??'');
async function data(){[site,menu]=await Promise.all([fetch('./content/site.json').then(r=>r.json()),fetch('./content/menu.json').then(r=>r.json())]);renderAll()}
function field(label,value,onchange,type='text',full=false){const wrap=document.createElement('label');if(full)wrap.className='full';wrap.textContent=label;const el=type==='textarea'?document.createElement('textarea'):document.createElement('input');if(type==='textarea')el.value=value??'';else{el.type=type;el.value=value??''}el.oninput=()=>onchange(el.value);wrap.append(el);return wrap}
function renderAll(){renderSections();renderMenu();renderTheme()}
function renderSections(){const box=$('#sections');box.innerHTML='';site.sections.sort((a,b)=>a.order-b.order).forEach((s,i)=>{const card=$('#section-template').content.cloneNode(true);card.querySelector('.label').textContent=`${s.type.toUpperCase()} · ${s.id}`;const fields=card.querySelector('.fields');const c=s.content||{},set=s.settings||{};fields.append(field('Section ID',s.id,v=>s.id=v),field('Type',s.type,v=>s.type=v),field('Visible',String(s.visible!==false),v=>s.visible=v==='true'),field('Display order',s.order,v=>s.order=Number(v),'number'));Object.keys(c).forEach(k=>fields.append(field(`Content: ${k}`,typeof c[k]==='object'?JSON.stringify(c[k]):c[k],v=>{try{c[k]=v.startsWith('{')||v.startsWith('[')?JSON.parse(v):v}catch{c[k]=v}},k==='body'||k==='title'?'textarea':'text',k==='body')));Object.keys(set).forEach(k=>fields.append(field(`Layout: ${k}`,set[k],v=>set[k]=isNaN(v)?v:Number(v))));card.querySelector('.up').onclick=()=>move(site.sections,i,-1);card.querySelector('.down').onclick=()=>move(site.sections,i,1);card.querySelector('.duplicate').onclick=()=>{let n=clone(s);n.id=`${s.type}-${Date.now()}`;n.order=Math.max(...site.sections.map(x=>x.order))+1;site.sections.push(n);renderSections()};card.querySelector('.remove').onclick=()=>{if(confirm(`Delete ${s.id}?`)){site.sections.splice(i,1);renderSections()}};box.append(card)})}
function move(arr,i,d){let j=i+d;if(j<0||j>=arr.length)return;[arr[i],arr[j]]=[arr[j],arr[i]];arr.forEach((x,n)=>x.order=n+1);renderSections()}
function renderMenu(){const box=$('#menu-items');box.innerHTML='';menu.sort((a,b)=>a.order-b.order).forEach((m,i)=>{const e=document.createElement('article');e.className='menu-editor';e.innerHTML=`<div class="row"><b>${esc(m.name||'New item')}</b><span><button class="up">↑</button><button class="down">↓</button><button class="remove">Delete</button></span></div><div class="fields"></div>`;let f=e.querySelector('.fields');['name','category','price','currency','description','ingredients','imageUrl','tags','visible','order'].forEach(k=>f.append(field(k,m[k],v=>m[k]=k==='visible'?v==='true':k==='order'?Number(v):k==='tags'?v.split(',').map(x=>x.trim()).filter(Boolean):v,k==='description'||k==='ingredients'?'textarea':'text',k==='description'||k==='ingredients'));e.querySelector('.up').onclick=()=>move(menu,i,-1);e.querySelector('.down').onclick=()=>move(menu,i,1);e.querySelector('.remove').onclick=()=>{if(confirm('Delete item?')){menu.splice(i,1);renderMenu()}};box.append(e)})}
function renderTheme(){const box=$('#theme-form');box.innerHTML='';Object.entries(site.brand).forEach(([k,v])=>box.append(field(`Brand: ${k}`,v,x=>site.brand[k]=x)));Object.entries(site.theme).forEach(([k,v])=>box.append(field(`Theme: ${k}`,v,x=>site.theme[k]=isNaN(x)?x:Number(x))));Object.entries(site.footer).forEach(([k,v])=>{if(typeof v!=='object')box.append(field(`Footer: ${k}`,v,x=>site.footer[k]=x))})}
async function publish(path,data){const token=await user.getIdToken();let r=await fetch('/api/publish',{method:'POST',headers:{'content-type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({action:'save-json',path,data})});if(!r.ok)throw new Error((await r.json()).error||'Publish failed')}
async function save(){try{$('#status').textContent='Publishing to GitHub…';await publish('content/site.json',site);await publish('content/menu.json',menu);$('#status').textContent='Published. Cloudflare Pages will deploy the commit.'}catch(e){$('#status').textContent='Error: '+e.message}}
$('#add-section').onclick=()=>{site.sections.push({id:`text-${Date.now()}`,type:'text',order:site.sections.length+1,visible:true,settings:{background:'#FBF8F1',align:'left',animation:'fade-up',delay:0},content:{eyebrow:'New section',title:'New title',body:'Write your content here.'}});renderSections()};$('#add-item').onclick=()=>{menu.push({id:`item-${Date.now()}`,order:menu.length+1,visible:true,category:'Chaat',name:'New menu item',price:'0.00',currency:'$',description:'Description',ingredients:'Ingredients',tags:[],imageUrl:''});renderMenu()};
document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==t.dataset.view)});$('#upload').onclick=async()=>{let file=$('#media-file').files[0];if(!file)return;let ok=['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type),limit=file.type.startsWith('video/')?15:5;if(!ok||file.size>limit*1024*1024){$('#upload-result').textContent='Unsupported file or too large.';return}let token=await user.getIdToken(),base64=await new Promise((res,rej)=>{let r=new FileReader;r.onload=()=>res(r.result.split(',')[1]);r.onerror=rej;r.readAsDataURL(file)});let r=await fetch('/api/publish',{method:'POST',headers:{'content-type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({action:'upload-media',name:file.name.replace(/[^a-z0-9._-]/gi,'-'),contentType:file.type,base64})});let out=await r.json();$('#upload-result').textContent=out.ok?`Uploaded: ${out.path}`:(out.error||'Upload failed')};
const bar=document.createElement('button');bar.textContent='Publish all changes';bar.style.cssText='position:fixed;right:24px;bottom:24px;background:#c5673d;color:#fff;border:0;border-radius:999px;padding:14px 20px;font-weight:700;box-shadow:0 8px 24px #0003';bar.onclick=save;document.body.append(bar);
$('#signin').onclick=async()=>{try{await firebase.auth().signInWithEmailAndPassword($('#email').value,$('#password').value)}catch(e){$('#auth-error').textContent='Sign-in failed'}};$('#logout').onclick=()=>firebase.auth().signOut();firebase.auth().onAuthStateChanged(async u=>{if(!u)return;user=u;$('#login').hidden=true;$('#app').hidden=false;$('#user').textContent=u.email;await data()});